name: Checks
on:
  push:

  pull_request:
    branches: [main]

env:
  PYTEST_ADDOPTS: --color=yes
  PIP_PROGRESS_BAR: "off"
defaults:
  run:
    # -l: login shell, needed when using Conda:
    shell: bash -l {0}

jobs:
  pytest:
    name: pytest (${{ matrix.os }}/${{ matrix.python-version }}
    runs-on: ${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
        os:
          - linux
        include:
          - os: linux
            os-version: ubuntu-22.04
          - install-mode: dev
            python-version: "3.11"
            coverage: "true"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          channels: conda-forge
          activate-environment: ogrre_data_cleaning_env

      - name: Install (dev)
        run: |
          pip install .[test]

      - name: Run pytest
        run: |
          pip install pytest  # ensure pytest is installed (should do nothing if already present from requirements-dev.txt)
          pytest --pyargs ogrre_data_cleaning --verbose
